# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: course_registeration.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ourse_registeration.proto\"=\n\x10\x41\x64\x64\x43ourseRequest\x12\x13\n\x0b\x63ourse_code\x18\x01 \x01(\t\x12\x14\n\x0c\x63ourse_title\x18\x02 \x01(\t\"5\n\x11\x41\x64\x64\x43ourseResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"W\n\x16RegisterStudentRequest\x12\x13\n\x0b\x63ourse_code\x18\x01 \x01(\t\x12\x12\n\nstudent_id\x18\x02 \x01(\t\x12\x14\n\x0cstudent_name\x18\x03 \x01(\t\";\n\x17RegisterStudentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x14\n\x12ListCoursesRequest\"/\n\x13ListCoursesResponse\x12\x18\n\x07\x63ourses\x18\x01 \x03(\x0b\x32\x07.Course\"*\n\x13ListStudentsRequest\x12\x13\n\x0b\x63ourse_code\x18\x01 \x01(\t\"T\n\x14ListStudentsResponse\x12\x1a\n\x08students\x18\x01 \x03(\x0b\x32\x08.Student\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"3\n\x06\x43ourse\x12\x13\n\x0b\x63ourse_code\x18\x01 \x01(\t\x12\x14\n\x0c\x63ourse_title\x18\x02 \x01(\t\"3\n\x07Student\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x14\n\x0cstudent_name\x18\x02 \x01(\t2\x85\x02\n\x12\x43ourseRegistration\x12\x32\n\tAddCourse\x12\x11.AddCourseRequest\x1a\x12.AddCourseResponse\x12\x44\n\x0fRegisterStudent\x12\x17.RegisterStudentRequest\x1a\x18.RegisterStudentResponse\x12\x38\n\x0bListCourses\x12\x13.ListCoursesRequest\x1a\x14.ListCoursesResponse\x12;\n\x0cListStudents\x12\x14.ListStudentsRequest\x1a\x15.ListStudentsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'course_registeration_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ADDCOURSEREQUEST']._serialized_start=30
  _globals['_ADDCOURSEREQUEST']._serialized_end=91
  _globals['_ADDCOURSERESPONSE']._serialized_start=93
  _globals['_ADDCOURSERESPONSE']._serialized_end=146
  _globals['_REGISTERSTUDENTREQUEST']._serialized_start=148
  _globals['_REGISTERSTUDENTREQUEST']._serialized_end=235
  _globals['_REGISTERSTUDENTRESPONSE']._serialized_start=237
  _globals['_REGISTERSTUDENTRESPONSE']._serialized_end=296
  _globals['_LISTCOURSESREQUEST']._serialized_start=298
  _globals['_LISTCOURSESREQUEST']._serialized_end=318
  _globals['_LISTCOURSESRESPONSE']._serialized_start=320
  _globals['_LISTCOURSESRESPONSE']._serialized_end=367
  _globals['_LISTSTUDENTSREQUEST']._serialized_start=369
  _globals['_LISTSTUDENTSREQUEST']._serialized_end=411
  _globals['_LISTSTUDENTSRESPONSE']._serialized_start=413
  _globals['_LISTSTUDENTSRESPONSE']._serialized_end=497
  _globals['_COURSE']._serialized_start=499
  _globals['_COURSE']._serialized_end=550
  _globals['_STUDENT']._serialized_start=552
  _globals['_STUDENT']._serialized_end=603
  _globals['_COURSEREGISTRATION']._serialized_start=606
  _globals['_COURSEREGISTRATION']._serialized_end=867
# @@protoc_insertion_point(module_scope)
